// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// piSugar
double piSugar(const int N);
RcppExport SEXP _StatComp20060_piSugar(SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(piSugar(N));
    return rcpp_result_gen;
END_RCPP
}
// pdfLaplaceC
double pdfLaplaceC(double x);
RcppExport SEXP _StatComp20060_pdfLaplaceC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(pdfLaplaceC(x));
    return rcpp_result_gen;
END_RCPP
}
// rwMetroC
List rwMetroC(double sigma, int N, double xinitial);
RcppExport SEXP _StatComp20060_rwMetroC(SEXP sigmaSEXP, SEXP NSEXP, SEXP xinitialSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type xinitial(xinitialSEXP);
    rcpp_result_gen = Rcpp::wrap(rwMetroC(sigma, N, xinitial));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StatComp20060_piSugar", (DL_FUNC) &_StatComp20060_piSugar, 1},
    {"_StatComp20060_pdfLaplaceC", (DL_FUNC) &_StatComp20060_pdfLaplaceC, 1},
    {"_StatComp20060_rwMetroC", (DL_FUNC) &_StatComp20060_rwMetroC, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_StatComp20060(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
