# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title PI
#' @description Use Monte Carlo to calculate PI using Rcpp
#' @param N the number of samples
#' @return PI
#' @examples
#' \dontrun{
#' pi <- piSugar(1000)
#' }
#' @export
piSugar <- function(N) {
    .Call(`_StatComp20060_piSugar`, N)
}

#' @title  The density function of the standard Laplace distribution 
#' @description Calculate density function of the standard Laplace distribution using Rcpp
#' @param x vector of quantiles.
#' @return the density
#' @examples
#' \dontrun{
#' f <- pdfLaplaceC(1)
#' }
#' @export
pdfLaplaceC <- function(x) {
    .Call(`_StatComp20060_pdfLaplaceC`, x)
}

#' @title A random walk Metropolis sampler for the standard Laplace distribution using Rcpp
#' @description A random walk Metropolis sampler for generating the standard Laplace distribution using Rcpp
#' @param sigma the variance
#' @param N the length of the chain
#' @param xinitial the initial value
#' @return a list with two components:x and k give the chain and the number of candidate points rejected
#' @examples
#' \dontrun{
#' rw<- Metro.rw(2,3000,25)
#' }
#' @export
rwMetroC <- function(sigma, N, xinitial) {
    .Call(`_StatComp20060_rwMetroC`, sigma, N, xinitial)
}

